
const LOGO="assets/logo.png";
const $=s=>document.querySelector(s),K='jony_school_v1';
const fmt=n=>Math.round(+n).toLocaleString('ru-RU').replace(/,/g,' ');
const ld=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),td=()=>ld(new Date());
let GD=0,SEL=new Set(),VIS=[],CM=new Date(),CD=td(),AM=new Date(),ALO=0,AS=0,U=null,V='home',Q='',GF='',PF='',AG=0,AD=td(),NV=0;
function seed(){const N=['Hasan Karimov','Madina Aliyeva','Jasur Toshmatov','Dilnoza Rahimova','Sardor Yusupov','Zilola Nazarova','Bekzod Qodirov','Malika Ergasheva','Otabek Sobirov','Nigora Karimova','Aziz Mirzayev','Sevara Umarova'];
const g=[{id:1,name:'IT Beginner',course:'IT',teacher:1,time:'Du-Chor-Ju 15:00',price:300000},{id:2,name:'English Intermediate',course:'English',teacher:2,time:'Sesh-Pay-Shan 17:00',price:250000},{id:3,name:'IELTS',course:'English',teacher:2,time:'Du-Chor-Ju 18:30',price:400000}];
const s=N.map((n,i)=>{const G=g[i%3],p=[1,.4,0,1][i%4]*G.price;return{id:i+1,name:n,phone:'+998 9'+(i%10)+' 123 45 '+(10+i),group:G.id,price:G.price,paid:p}});
return{students:s,groups:g,teachers:[{id:1,name:'Ali Valiyev',phone:'+998 90 111 22 33',subject:'IT',salary:4500000,email:'teacher@jony.uz'},{id:2,name:'Nodira Saidova',phone:'+998 91 222 33 44',subject:'English',salary:4000000,email:'nodira@jony.uz'}],
courses:[{id:1,name:'English',price:250000},{id:2,name:'IT',price:300000},{id:3,name:'IELTS',price:400000}],ann:[{id:1,title:'Yangi o‘quv yili boshlandi',text:'Barcha guruhlar dars jadvali bilan tanishing.',status:'Published'}],
msgs:[],pay:[],att:{},logs:[],notes:[{t:'⚠️ To‘lov muddati yaqinlashdi',r:0},{t:'📚 Yangi guruh yaratildi',r:0}]}}
let D;try{D=JSON.parse(localStorage.getItem(K))}catch(e){}D=D||seed();const P=['View','Create','Edit','Delete','Export','Manage'];D.media=D.media||[];D.ev=D.ev||[];D.contact=D.contact||{phone:'+998 71 123 45 67',email:'info@jony.uz',tg:'@jony_school',addr:'Toshkent shahri'};D.users=D.users||[{id:1,name:'Admin',email:'admin@jony.uz',pw:'admin123',role:'Super Admin'}];D.perm=D.perm||Object.fromEntries(['Super Admin','Admin','Moderator','Teacher'].map(r=>[r,Object.fromEntries(P.map(p=>[p,(r=='Super Admin'||(r=='Admin'&&p!='Manage')||(r=='Moderator'&&['View','Create','Edit'].includes(p))||(r=='Teacher'&&p=='View'))?1:0]))]));
const save=()=>{try{localStorage.setItem(K,JSON.stringify(D))}catch(e){}};
const nid=a=>a.reduce((m,x)=>Math.max(m,x.id),0)+1;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const IC={home:'home',students:'students',groups:'groups',courses:'courses',teachers:'teachers',att:'attendance',pay:'payments',rep:'reports',ann:'announcements',msgs:'contact',media:'media',cal:'calendar',an:'analytics',adm:'admin',logs:'logs',out:'logout',money:'money',warn:'warning',chk:'check',clk:'clock',crs:'cross',bell:'bell',sun:'sun'};
const ii=(k,c='ii')=>`<img class="${c}" src="assets/icons/${IC[k]}.png" alt="" draggable="false">`,hi=k=>ii(k,'hi');
const ico=(k,e)=>IC[k]?`<img class="ni" src="assets/icons/${IC[k]}.png" alt="" draggable="false">`:e;
const dkey=(y,m,d)=>y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0');
const pno=()=>'№'+String(D.pay.reduce((m,p)=>Math.max(m,parseInt(String(p.no).replace(/\D/g,''))||0),0)+1).padStart(5,'0');
// notifications: har bir foydalanuvchi uchun alohida (o‘qilgan / tozalangan). to:'staff' = barcha admin panel foydalanuvchilari (Super Admin ham, keyin qo‘shilganlar ham)
const vn=()=>D.notes.filter(n=>(!n.to||U.role=='admin')&&!(n.hd||[]).includes(U.email));
const unr=n=>!n.r&&!(n.rb||[]).includes(U.email);
const AL={k:['✓','Keldi'],l:['⏱','Kechikdi'],x:['✕','Kelmadi']};
const WD=['Yak','Du','Se','Chor','Pay','Ju','Sha'],MN=['Yanvar','Fevral','Mart','Aprel','May','Iyun','Iyul','Avgust','Sentabr','Oktabr','Noyabr','Dekabr'];
const DM={du:1,dush:1,dushanba:1,se:2,sesh:2,seshanba:2,chor:3,chorshanba:3,pay:4,payshanba:4,ju:5,juma:5,sha:6,shan:6,shanba:6,yak:0,yakshanba:0};
const lds=g=>String(g.time||'').toLowerCase().split(/[^a-z]+/).map(x=>DM[x]).filter(x=>x!=null);

function toast(m,c=''){const e=document.createElement('div');e.className='t '+c;e.textContent=m;$('#ts').append(e);setTimeout(()=>e.remove(),3200)}
function log(a,t,o='',n=''){D.logs.unshift({who:U?U.name:'—',a,t,d:new Date().toLocaleString('ru-RU'),o,n});save()}
const G=id=>D.groups.find(g=>g.id==id)||{name:'—',price:0},T=id=>D.teachers.find(t=>t.id==id)||{name:'—'};
const mg=()=>U.role=='teacher'?D.groups.filter(g=>g.teacher==U.tid):D.groups;
const ms=()=>{const ids=mg().map(g=>g.id);return D.students.filter(s=>ids.includes(+s.group))};
const ps=s=>s.paid>=s.price?['ok','✓','To‘langan']:s.paid>0?['mid','◐','Qisman to‘langan']:['no','!','To‘lanmagan'];
const bg=s=>{const[c,i,t]=ps(s);return`<span class="bd ${c}">${i} ${t}</span>`};
const ini=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2);
const dl=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),10).toLocaleDateString('ru-RU')};
const M=[['home','🏠','Bosh sahifa'],['students','👨‍🎓','O‘quvchilar'],['groups','👥','Guruhlar'],['courses','📚','Kurslar','a'],['teachers','👨‍🏫','O‘qituvchilar','a'],['att','📅','Davomat'],['pay','💳','To‘lovlar','a'],['rep','📊','Hisobotlar','a'],['ann','📢','E‘lonlar','a'],['msgs','📨','Admin bilan bog‘lanish'],['media','🖼️','Media Center','a'],['cal','🗓️','Calendar'],['an','📈','Analytics','a'],['adm','👑','Admin va rollar','a'],['logs','📝','Activity Logs','a']];
function loginUI(){return`<div class="lg"><form class="card" onsubmit="return login(event)"><div style="text-align:center"><div style="display:flex;justify-content:center;margin-bottom:10px">${lg(78)}</div><h2 style="margin:16px 0 2px">JONY SCHOOL</h2><div class="mut">Academy Management</div></div>
<label>Email</label><input id="em" type="email" required autocomplete="username"><label>Parol</label><input id="pw" type="password" required autocomplete="current-password">
<label class="rm"><input type="checkbox" id="rm"> Meni eslab qol (60 kun qayta kirish shart emas)</label><button class="btn" style="width:100%">Kirish</button></form></div>`}
const SK='jony_sess_v1',SD=60*864e5;
function mkU(m){const us=D.users.find(x=>x.email==m);if(us)return{role:'admin',name:us.name,prole:us.role,email:us.email};if(m=='teacher@jony.uz')return{role:'teacher',name:'Ali Valiyev',tid:1,prole:'Teacher',email:m};return null}
function login(e){e.preventDefault();const m=$('#em').value.trim(),p=$('#pw').value,rm=$('#rm')&&$('#rm').checked;
const us=D.users.find(x=>x.email==m&&x.pw==p);if(us||(m=='teacher@jony.uz'&&p=='teacher123'))U=mkU(m);else{toast('❌ Email yoki parol noto‘g‘ri','e');return false}
try{if(rm)localStorage.setItem(SK,JSON.stringify({e:U.email,x:Date.now()+SD}));else localStorage.removeItem(SK)}catch(x){}
V='home';NV=1;log('Login','Tizim');render();toast('✅ Xush kelibsiz, '+U.name);return false}
function restore(){try{const r=JSON.parse(localStorage.getItem(SK)||'null');if(r&&r.x>Date.now()){const u=mkU(r.e);if(u){U=u;NV=1;localStorage.setItem(SK,JSON.stringify({e:r.e,x:Date.now()+SD}));return}}localStorage.removeItem(SK)}catch(x){}}
function logout(){U=null;try{localStorage.removeItem(SK)}catch(x){}render()}
function shell(){const un=vn().filter(unr).length;
return`<div class="app ${localStorage.jc=='1'?'col':''}" id="ap"><aside id="sb"><div class="brand">${lg(40)}<span class="lb">JonySchool</span></div>
${M.filter(m=>m[3]!='a'||U.role=='admin').map(m=>`<button class="nav ${(V==m[0]||(V=='gd'&&m[0]=='groups'))?'on':''}" onclick="go('${m[0]}')" title="${m[2]}"><span class="ni-w">${ico(m[0],m[1])}</span><span class="lb">${m[2]}</span></button>`).join('')}
<button class="nav" onclick="logout()"><span class="ni-w">${ico('out','🚪')}</span><span class="lb">Chiqish</span></button><div class="dm"><span>🌙</span><span class="lb">Dark Mode</span><button class="sw" onclick="th()" aria-label="Dark mode"><i></i></button></div></aside>
<div class="mn"><div class="top"><button class="ib hb" onclick="$('#sb').classList.toggle('open')">☰</button><button class="ib cl" onclick="localStorage.jc=localStorage.jc=='1'?'0':'1';$('#ap').classList.toggle('col')">←</button>
<div class="srch"><input id="gs" placeholder="🔍 Qidiruv: o‘quvchi, o‘qituvchi, guruh..." oninput="gsearch(this.value)"><div class="dd" id="dd" hidden></div></div><div class="sp"></div>
<button class="ib" id="bl" onclick="bell()">${ii('bell')}${un?`<span class="bd no" style="position:absolute;top:-6px;right:-6px;padding:0 6px">${un}</span>`:''}</button><button class="ib" onclick="th()" title="Dark mode">${ii('sun')}</button>
<div class="pf"><span class="av">${ini(U.name)}</span><div><b>${U.name}</b><div class="mut">${U.prole||'Admin'}</div></div></div><div class="dd" id="nb" hidden style="left:auto;width:290px"></div></div><div id="main"></div></div></div>`}
function th(){const r=document.documentElement,d=r.dataset.theme=='dark'||(!r.dataset.theme&&matchMedia('(prefers-color-scheme:dark)').matches);r.dataset.theme=d?'light':'dark';try{localStorage.jt=r.dataset.theme}catch(e){}}
function bell(){const b=$('#nb');b.hidden=!b.hidden;if(b.hidden)return;const L=vn();
b.innerHTML=L.map(n=>`<div ${n.g?`onclick="go('${n.g}')"`:''} style="${unr(n)?'font-weight:700':''}">${n.t}</div>`).join('')||'<div>Bo‘sh</div>';if(L.length)b.innerHTML+='<div onclick="cln()">🗑 Tozalash</div>';
L.forEach(n=>{if(unr(n))(n.rb=n.rb||[]).push(U.email)});save();const bl=$('#bl'),x=bl&&bl.querySelector('.bd');x&&x.remove()}
function cln(){vn().forEach(n=>(n.hd=n.hd||[]).push(U.email));save();render();toast('✅ Tozalandi')}
function gsearch(q){q=q.toLowerCase();const d=$('#dd');if(!q){d.hidden=true;return}
const r=[...ms().filter(s=>(s.name+s.phone).toLowerCase().includes(q)).map(s=>['👨‍🎓 '+s.name,'students']),...D.groups.filter(g=>g.name.toLowerCase().includes(q)).map(g=>['👥 '+g.name,'groups']),...(U.role=='admin'?[...D.teachers.filter(t=>t.name.toLowerCase().includes(q)).map(t=>['👨‍🏫 '+t.name,'teachers']),...D.courses.filter(c=>c.name.toLowerCase().includes(q)).map(c=>['📚 '+c.name,'courses']),...D.msgs.filter(m=>(m.name+m.subj).toLowerCase().includes(q)).map(m=>['📨 '+m.subj,'msgs'])]:[])];
d.hidden=false;d.innerHTML=r.slice(0,8).map(x=>`<div onclick="go('${x[1]}')">${x[0]}</div>`).join('')||'<div>Topilmadi</div>'}
function go(v){if(v!='students')SEL.clear();if(v=='att')AS=1;V=v;NV=1;$('#sb')&&$('#sb').classList.remove('open');render()}
function render(){if(!U){$('#app').innerHTML=loginUI();return}$('#app').innerHTML=shell();const mm=$('#main');mm.innerHTML=VW[V]();if(NV){NV=0;mm.classList.add('enter')}if(V=='students')stTb();if(V=='att'&&AS){AS=0;const w=$('#atw'),c=$('#tdc');if(w&&c)w.scrollLeft=Math.max(0,c.offsetLeft-w.clientWidth/2)}}
// modal & forms
function mo(h){const m=document.createElement('div');m.className='mo';m.innerHTML=`<div class="card">${h}</div>`;m.onclick=e=>{if(e.target==m)m.remove()};document.body.append(m)}
const cm=()=>document.querySelector('.mo')?.remove();
const opt=(a,v)=>a.map(x=>`<option value="${x[0]}" ${x[0]==v?'selected':''}>${x[1]}</option>`).join('');
const FD={users:['Admin',[['name','Ism'],['email','Email'],['pw','Parol'],['role','Rol','r']]],ev:['Tadbir',[['date','Sana','d'],['text','Tadbir']]],media:['Rasm',[]],students:['O‘quvchi',[['name','Ism Familiya'],['phone','Telefon'],['group','Guruh','g'],['price','Oylik to‘lov','n']]],teachers:['O‘qituvchi',[['name','Ism Familiya'],['phone','Telefon'],['subject','Fan'],['salary','Oylik maosh','n'],['email','Email']]],groups:['Guruh',[['name','Guruh nomi'],['course','Kurs','c'],['teacher','O‘qituvchi','t'],['time','Jadval / vaqt'],['price','Oylik to‘lov','n']]],courses:['Kurs',[['name','Kurs nomi'],['price','Oylik narx','n']]],ann:['E‘lon',[['title','Sarlavha'],['text','Tavsif'],['status','Holat','s']]]};
function fm(k,id){const[t,f]=FD[k],o=id?D[k].find(x=>x.id==id):{};
mo(`<h3>${id?'✏️ Tahrirlash':'➕ Qo‘shish'}: ${t}</h3>`+f.map(([n,l,ty])=>`<label>${l}</label>`+(ty=='g'?`<select id="f_${n}">${opt(mg().map(g=>[g.id,g.name]),o[n])}</select>`:ty=='c'?`<select id="f_${n}">${opt(D.courses.map(c=>[c.name,c.name]),o[n])}</select>`:ty=='t'?`<select id="f_${n}">${opt(D.teachers.map(c=>[c.id,c.name]),o[n])}</select>`:ty=='r'?`<select id="f_${n}">${opt(Object.keys(D.perm).map(x=>[x,x]),o[n])}</select>`:ty=='s'?`<select id="f_${n}">${opt(['Draft','Published','Archived'].map(x=>[x,x]),o[n])}</select>`:`<input id="f_${n}" type="${ty=='n'?'number':ty=='d'?'date':'text'}" value="${o[n]??''}">`)).join('')+`<br><br><button class="btn g" onclick="sv('${k}',${id||0})">Saqlash</button> <button class="btn o" onclick="cm()">Bekor</button>`)}
function sv(k,id){const o={};FD[k][1].forEach(([n,,ty])=>{let v=$('#f_'+n).value.trim();if(ty=='n'||ty=='g'||ty=='t')v=+v;o[n]=v});
if(!(o.name||o.title||o.text)){toast('⚠️ Nomni kiriting','w');return}
if(k=='users'&&(!o.email||!o.pw||D.users.some(u=>u.email==o.email&&u.id!=id))){toast('⚠️ Email va parolni kiriting (email takrorlanmasin)','w');return}
if(id){const x=D[k].find(z=>z.id==id);Object.assign(x,o)}else{o.id=nid(D[k]);if(k=='students')o.paid=0;D[k].push(o);D.notes.unshift(k=='users'?{t:'👑 Yangi admin qo‘shildi: '+esc(o.name)+' ('+esc(o.role)+')',r:0,to:'staff',g:'adm'}:{t:'📚 Yangi '+FD[k][0]+': '+esc(o.name||o.title||o.text),r:0})}
log(id?'Tahrirlandi':'Yaratildi',FD[k][0]+': '+(o.name||o.title||o.text));cm();render();toast('✅ Saqlandi')}
function del(k,id){if(!D.perm[U.prole].Delete){toast('⚠️ Sizda o‘chirish huquqi yo‘q','w');return}const x=D[k].find(z=>z.id==id);if(!x)return;const nm=x.name||x.title||x.text||'';
ask({t:'O‘chirilsinmi?',m:(nm?'<b>'+esc(nm)+'</b><br>':'')+(k=='groups'?'Guruh va undagi barcha o‘quvchilar o‘chiriladi.':'Bu amalni ortga qaytarib bo‘lmaydi.'),y:'Ha, o‘chirish'},()=>{D[k]=D[k].filter(z=>z.id!=id);if(k=='groups')D.students=D.students.filter(z=>z.group!=id);log('O‘chirildi',FD[k][0]+': '+nm);render();toast('✅ O‘chirildi')})}
const acts=k=>`<td><button class="btn o s" onclick="fm('${k}',ID)">✏️</button> <button class="btn r s" onclick="del('${k}',ID)">🗑</button></td>`;
const A=(k,id)=>acts(k).replace(/ID/g,id);
// views
const VW={
home(){const s=ms(),t=td(),st=x=>D.att[t+'|'+x.id],k=s.filter(x=>st(x)=='k').length,l=s.filter(x=>st(x)=='l').length,xx=s.filter(x=>st(x)=='x').length,mk=k+l+xx,pr=k+l,pct=mk?Math.round(pr/mk*100):0,inc=D.pay.filter(p=>p.date==t).reduce((a,p)=>a+p.amount,0),db=s.filter(x=>x.paid<x.price).length,ad=U.role=='admin',cr=2*Math.PI*36,y=t.slice(0,4),ann=D.ann.find(a=>a.status=='Published'),by=D.attby&&D.attby[t+'|'+(mg()[0]||{}).id];
const c=[['c1',ii('students'),'Jami o‘quvchilar',s.length,'Faol o‘quvchilar'],['c2',ii('groups'),'Jami guruhlar',mg().length,'Ochiq guruhlar'],['c3',ii('teachers'),'O‘qituvchilar',D.teachers.length,'Jamoa'],['c4',ii('att'),'Bugungi davomat',pr+'/'+s.length,mk?pct+'% davomat':'Belgilanmagan'],['c5',ii('money'),'Bugungi tushum',fmt(inc),'so‘m'],['c6',ii('warn'),'Qarzdorlar',db,Math.round(db/(s.length||1)*100)+'% o‘quvchilar']];
const rv=['Yan','Fev','Mar','Apr','May','Iyn','Iyl','Avg','Sen','Okt','Noy','Dek'].map((n,i)=>({n,t:'',v:D.pay.filter(p=>p.date.slice(0,7)==y+'-'+String(i+1).padStart(2,'0')).reduce((a,p)=>a+p.amount,0)}));
return`<div class="grid g6">${c.map(x=>`<div class="sc ${x[0]}"><span class="sci">${x[1]}</span><div><div class="scl">${x[2]}</div><div class="scn">${x[3]}</div><div class="scs">${x[4]}</div></div></div>`).join('')}</div>
<div class="dg"><div class="dl"><div class="two"><div class="card"><b class="ct">${hi('rep')} Davomat statistikasi</b><div class="ar"><div class="am ok"><div class="amr">${ii('chk')}<b>${k}</b></div>Keldi</div><div class="am mid"><div class="amr">${ii('clk')}<b>${l}</b></div>Kechikdi</div><div class="am no"><div class="amr">${ii('crs')}<b>${xx}</b></div>Kelmadi</div><svg viewBox="0 0 84 84" width="84"><circle cx="42" cy="42" r="36" fill="none" stroke="var(--lb)" stroke-width="9"/><circle cx="42" cy="42" r="36" fill="none" stroke="var(--gr)" stroke-width="9" stroke-linecap="round" stroke-dasharray="${pct/100*cr} ${cr}" transform="rotate(-90 42 42)"/><text x="42" y="47" text-anchor="middle" font-weight="800" fill="currentColor">${pct}%</text></svg></div><div class="bar"><i style="width:${pct}%"></i></div></div>
<div class="card mb"><b class="ct">${hi('rep')} Oylik daromad · ${y}</b>${bx(rv)}</div></div>
<div class="card"><div class="h"><b class="ct" style="flex:1">${hi('students')} So‘nggi o‘quvchilar</b><button class="btn o s" onclick="go('students')">Barchasi</button></div><div class="grid" style="margin:0">${s.slice(-4).reverse().map(x=>`<div class="card" style="text-align:center;cursor:pointer" onclick="go('students')"><span class="av" style="width:52px;height:52px;margin:0 0 6px">${ini(x.name)}</span><div><b>${x.name}</b></div><div class="mut">${G(x.group).name}</div>${bg(x)}<div class="mut">${pc(sAtt(x.id))} davomat</div></div>`).join('')||'<p class="mut">O‘quvchi yo‘q</p>'}</div></div>
<div class="card"><b>⚡ Tezkor amallar</b><div class="qa"><button class="btn" onclick="fm('students')">➕ O‘quvchi qo‘shish</button>${ad?`<button class="btn g" onclick="fm('groups')">➕ Guruh qo‘shish</button><button class="btn pu" onclick="go('pay')">💳 To‘lov</button><button class="btn" onclick="go('rep')">📄 Hisobot</button>`:`<button class="btn g" onclick="go('att')">📅 Davomat</button>`}</div></div></div>
<div class="dr"><div class="promo">${lg(56)}<div><b style="font-size:18px">JonySchool</b><div>Bilim — kelajak kaliti!</div></div></div>
<div class="card"><b class="ct">${hi('ann')} So‘nggi yangiliklar</b>${vn().slice(0,4).map(n=>`<p class="mut">${n.t}</p>`).join('')||'<p class="mut">Yangilik yo‘q</p>'}</div>
<div class="card"><b class="ct">${hi('cal')} Yaqin muddatlar</b><p>💳 To‘lov muddati: ${dl()}<br><span class="mut">${db} ta qarzdor</span></p><p>📅 Davomat: ${mk?mk+'/'+s.length+' belgilandi':'bugun belgilanmagan'}${by?`<br><span class="mut">${by.by}, ${by.t}</span>`:''}</p>${ann?`<p>📢 ${ann.title}</p>`:''}</div>
<div class="card"><b class="ct">${hi('msgs')} Admin bilan bog‘lanish</b><p class="mut">Savol yoki taklif bo‘lsa yozing.</p><button class="btn" style="width:100%" onclick="go('msgs')">✉ Bog‘lanish</button></div></div></div>`},
students(){return`<div class="h"><h2>${hi('students')} O‘quvchilar</h2><button class="btn r" id="bd" onclick="bulk()" ${SEL.size?'':'hidden'}>🗑 O‘chirish (${SEL.size})</button><button class="btn" onclick="fm('students')">➕ Add Student</button></div><div class="card"><div class="grid" style="margin:0 0 10px"><input placeholder="Ism, telefon, guruh..." value="${Q}" oninput="Q=this.value;stTb()"><select onchange="GF=this.value;stTb()"><option value="">Barcha guruhlar</option>${opt(mg().map(g=>[g.id,g.name]),GF)}</select><select onchange="PF=this.value;stTb()"><option value="">Barcha to‘lovlar</option>${opt([['ok','To‘langan'],['mid','Qisman'],['no','To‘lanmagan']],PF)}</select></div><div class="tw" id="tb"></div></div>`},
groups(){return`<div class="h"><h2>${hi('groups')} Guruhlar</h2>${U.role=='admin'?'<button class="btn" onclick="fm(\'groups\')">➕ Guruh qo‘shish</button>':''}</div><div class="grid">${mg().map(g=>{const s=D.students.filter(x=>x.group==g.id);return`<div class="card" style="cursor:pointer" onclick="GD=${g.id};go('gd')"><b style="font-size:18px">${g.name}</b><div class="mut">${g.course} · ${T(g.teacher).name}</div><p>🕒 ${g.time}<br>👨‍🎓 ${s.length} o‘quvchi<br>💰 ${fmt(g.price)} so‘m/oy<br>📈 Davomat: ${pc(gAtt(g.id))}</p><button class="btn o s" onclick="event.stopPropagation();AG=${g.id};go('att')">Davomat</button> ${U.role=='admin'?`<button class="btn o s" onclick="event.stopPropagation();fm('groups',${g.id})">✏️</button> <button class="btn r s" onclick="event.stopPropagation();del('groups',${g.id})">🗑</button>`:''}</div>`}).join('')}</div>`},
courses(){return`<div class="h"><h2>${hi('courses')} Kurslar</h2><button class="btn" onclick="fm('courses')">➕ Add Course</button></div><div class="grid">${D.courses.map(c=>{const gs=D.groups.filter(g=>g.course==c.name);return`<div class="card"><b style="font-size:18px">${c.name=='English'?'🇬🇧':c.name=='IT'?'💻':'📚'} ${c.name}</b><p>👥 ${gs.length} guruh<br>👨‍🎓 ${D.students.filter(s=>gs.some(g=>g.id==s.group)).length} o‘quvchi<br>💰 ${fmt(c.price)} so‘m<br><span class="bd ok">✓ Faol</span></p><button class="btn o s" onclick="fm('courses',${c.id})">✏️</button> <button class="btn r s" onclick="del('courses',${c.id})">🗑</button></div>`}).join('')}</div>`},
teachers(){return`<div class="h"><h2>${hi('teachers')} O‘qituvchilar</h2><button class="btn" onclick="fm('teachers')">➕ Teacher qo‘shish</button></div><div class="card tw"><table><tr><th>Ism</th><th>Telefon</th><th>Fan</th><th>Guruhlar</th><th>O‘quvchilar</th><th>Maosh</th><th>Holat</th><th></th></tr>${D.teachers.map(t=>{const gs=D.groups.filter(g=>g.teacher==t.id);return`<tr><td><span class="av">${ini(t.name)}</span>${t.name}</td><td>${t.phone}</td><td>${t.subject}</td><td>${gs.length}</td><td>${D.students.filter(s=>gs.some(g=>g.id==s.group)).length}</td><td>${fmt(t.salary)}</td><td><span class="bd ok">✓ Faol</span></td>${A('teachers',t.id)}</tr>`}).join('')}</table></div>`},
att(){const gs=mg();if(!gs.some(g=>g.id==AG))AG=gs[0]?.id;const g=G(AG),s=D.students.filter(x=>x.group==AG),y=AM.getFullYear(),m=AM.getMonth(),n=new Date(y,m+1,0).getDate(),t=td(),ls=lds(g),T0=new Date(t+'T00:00:00');
const days=[...Array(n)].map((_,i)=>{const d=i+1,k=dkey(y,m,d),w=new Date(y,m,d).getDay();return{d,k,w,ls:!ls.length||ls.includes(w),ag:Math.round((T0-new Date(k+'T00:00:00'))/864e5)}}).filter(x=>!ALO||!ls.length||x.ls||x.k==t||s.some(z=>D.att[x.k+'|'+z.id]));
const cnt=v=>s.reduce((a,z)=>a+days.filter(d=>D.att[d.k+'|'+z.id]==v).length,0),pct=z=>{const a=days.map(d=>D.att[d.k+'|'+z.id]).filter(Boolean);return a.length?Math.round(a.filter(v=>v!='x').length/a.length*100)+'%':'—'};
const cell=(z,d)=>{const v=D.att[d.k+'|'+z.id],fu=d.ag<0;return`<td class="act"><button class="ac ${v||''} ${d.ls?'':'nl'} ${fu?'fu':''}" style="${fu?'':'--o:'+Math.max(.32,1-d.ag*.035).toFixed(2)}" ${fu?'disabled':''} title="${v?AL[v][1]:'Belgilanmagan'} · ${d.k}" onclick="ap(event,${z.id},'${d.k}')">${v?AL[v][0]:''}</button></td>`};
return`<div class="h"><h2>${hi('att')} Davomat</h2><button class="btn" onclick="fm('students')">➕ O‘quvchi qo‘shish</button></div><div class="card"><div class="h" style="margin:0 0 10px"><select style="width:auto;min-width:200px;flex:1;max-width:320px" onchange="AG=+this.value;AS=1;render()">${opt(gs.map(x=>[x.id,x.name]),AG)}</select><button class="btn o s" onclick="am(-1)">◀</button><b style="min-width:120px;text-align:center">${MN[m]} ${y}</b><button class="btn o s" onclick="am(1)">▶</button><button class="btn o s" onclick="am(0)">Bugun</button>${ls.length?`<label style="display:flex;align-items:center;gap:6px;margin:0"><input type="checkbox" style="width:auto" ${ALO?'checked':''} onchange="ALO=this.checked?1:0;attRefresh()"> Faqat dars kunlari</label>`:''}</div>
<p style="margin:0 0 10px"><span class="bd ok">🟢 Keldi: ${cnt('k')}</span> <span class="bd mid">🟡 Kechikdi: ${cnt('l')}</span> <span class="bd no">🔴 Kelmadi: ${cnt('x')}</span> <span class="mut">· Doirachani bosing — Keldi / Kechikdi / Kelmadi. Kunlar o‘tgan sayin doirachalar xiralashadi.</span></p>
<div class="tw" id="atw" onscroll="closePP()"><table class="at2"><tr><th class="sn">O‘quvchi</th>${days.map(d=>`<th class="ah ${d.ag==0?'tdy':''} ${d.ls?'':'nl'}" ${d.ag==0?'id="tdc"':''}><span>${WD[d.w]}</span><b>${d.d}</b></th>`).join('')}<th class="ah"><span>Davomat</span><b>%</b></th></tr>
${s.map(z=>`<tr><td class="sn"><span class="av">${ini(z.name)}</span>${esc(z.name)}</td>${days.map(d=>cell(z,d)).join('')}<td><b>${pct(z)}</b></td></tr>`).join('')||'<tr><td class="mut sn">Bu guruhda o‘quvchi yo‘q</td></tr>'}</table></div></div>`},
pay(){const tt=s=>({ok:'To‘langan — bosing: to‘lanmadi (qaytarildi) deb belgilanadi',mid:'Qisman to‘langan — bosing: to‘liq to‘landi deb belgilanadi',no:'To‘lanmagan — bosing: to‘landi deb belgilanadi'}[ps(s)[0]]);
return`<div class="h"><h2>${hi('pay')} To‘lovlar</h2><button class="btn" onclick="fm('students')">➕ O‘quvchi qo‘shish</button></div><div class="card tw"><table><tr><th style="width:56px"></th><th>O‘quvchi</th><th>Guruh</th><th>To‘langan / Oylik</th><th>Qolgan</th><th>Deadline</th><th>Holat</th><th></th></tr>${D.students.map(s=>`<tr><td><button class="pc ${ps(s)[0]}" onclick="tp(${s.id})" title="${tt(s)}" aria-label="To‘lov holati">✓</button></td><td>${esc(s.name)}</td><td>${G(s.group).name}</td><td>${fmt(s.paid)} / ${fmt(s.price)}</td><td>${fmt(Math.max(0,s.price-s.paid))}</td><td>${dl()}</td><td>${bg(s)}</td><td>${s.paid<s.price?`<button class="btn g s" onclick="pm(${s.id})">To‘lov</button>`:''} <button class="btn r s" onclick="del('students',${s.id})">🗑</button></td></tr>`).join('')||'<tr><td class="mut">O‘quvchi yo‘q</td></tr>'}</table></div>`},
rep(){const gs=D.groups.map(g=>({n:g.name,v:D.students.filter(s=>s.group==g.id).reduce((a,s)=>a+s.paid,0)})),mx=Math.max(1,...gs.map(x=>x.v)),st=D.students,c=[st.filter(s=>s.paid>=s.price).length,st.filter(s=>s.paid>0&&s.paid<s.price).length,st.filter(s=>!s.paid).length],cl=['#17B26A','#E59A0B','#E5484D'],tt=st.length||1;let off=0;
return`<div class="h"><h2>${hi('rep')} Hisobotlar</h2><button class="btn o" onclick="csv()">CSV</button><button class="btn o" onclick="print()">🖨 Print / PDF</button></div><div class="two"><div class="card"><b>💰 Guruhlar bo‘yicha tushum</b><div class="bars">${gs.map(x=>`<div><span>${fmt(x.v/1000)}k</span><b style="height:${x.v/mx*140+4}px"></b>${x.n}</div>`).join('')}</div></div>
<div class="card"><b>To‘lov holati</b><svg viewBox="0 0 42 42" width="200" style="display:block;margin:auto"><circle cx="21" cy="21" r="15.9" fill="none" stroke="var(--lb)" stroke-width="6"/>${c.map((v,i)=>{const l=v/tt*100,e=`<circle cx="21" cy="21" r="15.9" fill="none" stroke="${cl[i]}" stroke-width="6" stroke-dasharray="${l} ${100-l}" stroke-dashoffset="${25-off}"/>`;off+=l;return e}).join('')}</svg><p style="text-align:center">🟢 ${c[0]} · 🟡 ${c[1]} · 🔴 ${c[2]}</p></div></div>
<div class="card" style="margin-top:16px"><b>🧾 To‘lov cheklari</b><div class="tw"><table>${D.pay.map((p,i)=>`<tr><td>${p.no}</td><td>${p.name}</td><td>${fmt(p.amount)}</td><td>${p.date}</td><td>${p.type}</td><td><button class="btn o s" onclick="rc(D.pay[${i}])">🧾</button> <button class="btn r s" onclick="dpay(${i})">🗑</button></td></tr>`).join('')||'<tr><td class="mut">Hali to‘lov yo‘q</td></tr>'}</table></div></div>`},
ann(){return`<div class="h"><h2>${hi('ann')} E‘lonlar</h2><button class="btn" onclick="fm('ann')">➕ E‘lon</button></div><div class="grid">${D.ann.map(a=>`<div class="card"><span class="bd ${a.status=='Published'?'ok':a.status=='Draft'?'mid':'nw'}">${a.status}</span><h3>${a.title}</h3><p class="mut">${a.text}</p><button class="btn o s" onclick="fm('ann',${a.id})">✏️</button> <button class="btn r s" onclick="del('ann',${a.id})">🗑</button></div>`).join('')}</div>`},
msgs(){const c=D.contact,ad=U.role=='admin',ce=ad&&D.perm[U.prole].Edit,tg=String(c.tg||'').replace(/^@/,''),row=(i,l,v,h)=>`<div class="ci"><span class="cic">${i}</span><div><div class="mut">${l}</div>${v?(h?`<a class="lk" href="${esc(h)}" target="_blank" rel="noopener"><b>${esc(v)}</b></a>`:`<b>${esc(v)}</b>`):'<b>—</b>'}</div></div>`;
return`<div class="h"><h2>${hi('msgs')} ADMIN BILAN BOG‘LANISH</h2></div><div class="two"><form class="card" onsubmit="return sm(event)"><label>Ism</label><input id="m1" required value="${esc(U.name)}"><label>Telefon</label><input id="m2" required><label>Email</label><input id="m3" type="email" required value="${esc(U.email||'')}"><label>Mavzu</label><input id="m4" required><label>Xabar</label><textarea id="m5" rows="3" required></textarea><br><br><button class="btn" id="mb" style="width:100%">XABAR YUBORISH</button></form>
<div class="card"><div class="h" style="margin:0 0 10px"><b style="flex:1">📇 Aloqa ma’lumotlari</b>${ce?'<button class="btn o s" onclick="editContact()">✏️ O‘zgartirish</button>':''}</div>${row('📞','Telefon',c.phone,c.phone?'tel:'+String(c.phone).replace(/[^\d+]/g,''):'')}${row('📧','Email',c.email,c.email?'mailto:'+c.email:'')}${row('💬','Telegram',c.tg,tg?'https://t.me/'+tg:'')}${row('📍','Manzil',c.addr,'')}</div></div>${ad?`<div class="card" style="margin-top:16px"><b>Kiruvchi xabarlar</b><div class="tw"><table>${D.msgs.map(m=>`<tr><td>${esc(m.name)}<br><span class="mut">${esc(m.subj)}</span><br><span class="mut">${esc([m.phone,m.email,m.d].filter(Boolean).join(' · '))}</span></td><td style="white-space:normal">${esc(m.text)}</td><td><span class="bd ${m.st==0?'nw':m.st==1?'mid':'ok'}">${['🔵 Yangi','🟡 Ko‘rib chiqilmoqda','🟢 Javob berildi'][m.st]}</span></td><td><button class="btn o s" onclick="ms2(${m.id},1)">O‘qildi</button> <button class="btn g s" onclick="ms2(${m.id},2)">Javob</button> <button class="btn r s" onclick="D.msgs=D.msgs.filter(x=>x.id!=${m.id});save();render()">🗑</button></td></tr>`).join('')||'<tr><td class="mut">Xabar yo‘q</td></tr>'}</table></div></div>`:''}`},
media(){return`<div class="h"><h2>${hi('media')} Media Center</h2><select id="mc" style="width:auto"><option>Logo</option><option>Banner</option><option>Gallery</option><option>News</option><option>Course</option></select><label class="btn" style="margin:0;display:inline-block">⬆ Upload<input type="file" accept="image/*" multiple hidden onchange="up(this)"></label></div><div class="grid">${D.media.map(m=>`<div class="card"><img src="${m.src}" alt="${m.name}" loading="lazy" style="width:100%;height:140px;object-fit:cover;border-radius:12px"><b>${m.name}</b><div class="mut">${m.cat}</div><button class="btn o s" onclick="rn(${m.id})">✏️</button> <button class="btn r s" onclick="del('media',${m.id})">🗑</button></div>`).join('')||'<div class="card mut">Rasm yuklash uchun Upload tugmasini bosing</div>'}</div>`},
cal(){const y=CM.getFullYear(),m=CM.getMonth(),f=(new Date(y,m,1).getDay()+6)%7,n=new Date(y,m+1,0).getDate(),c=['Du','Se','Chor','Pay','Ju','Sh','Yak'].map(x=>`<b class="mut">${x}</b>`);for(let i=0;i<f;i++)c.push('<i></i>');
for(let d=1;d<=n;d++){const k=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0');c.push(`<button class="cd ${k==CD?'on':''}" onclick="CD='${k}';render()">${d}<br><small>${[...new Set(evs(k).map(x=>x[0]))].join('')}</small></button>`)}
return`<div class="h"><h2>${hi('cal')} Calendar</h2><button class="btn o" onclick="CM=new Date(${y},${m-1},1);render()">◀</button><b>${CM.toLocaleDateString('uz',{month:'long',year:'numeric'})}</b><button class="btn o" onclick="CM=new Date(${y},${m+1},1);render()">▶</button></div><div class="two"><div class="card"><div class="cg">${c.join('')}</div></div><div class="card"><b>${CD}</b> <button class="btn s" onclick="fm('ev');$('#f_date').value=CD">➕ Tadbir</button>${evs(CD).map(e=>`<p>${e[0]} ${e[1]} ${e[2]?`<button class="btn r s" onclick="del('ev',${e[2]})">🗑</button>`:''}</p>`).join('')||'<p class="mut">Bu kunda ma’lumot yo‘q</p>'}</div></div>`},
an(){const sm=f=>D.pay.filter(f).reduce((a,p)=>a+p.amount,0),t=td(),dy=[...Array(7)].map((_,i)=>{const d=ld(new Date(Date.now()-(6-i)*864e5));return{n:d.slice(5),v:sm(p=>p.date==d)}}),wk=dy.reduce((a,x)=>a+x.v,0);
const ga=D.groups.map(g=>({n:g.name,v:gAtt(g.id)||0,t:pc(gAtt(g.id))})),gd=D.groups.map(g=>({n:g.name,v:D.students.filter(s=>s.group==g.id).reduce((a,s)=>a+Math.max(0,s.price-s.paid),0)}));
return`<div class="h"><h2>${hi('an')} Analytics</h2></div><div class="grid">${[['Kunlik',sm(p=>p.date==t)],['Haftalik',wk],['Oylik',sm(p=>p.date.slice(0,7)==t.slice(0,7))],['Yillik',sm(p=>p.date.slice(0,4)==t.slice(0,4))]].map(x=>`<div class="card stat"><div class="mut">${x[0]} tushum</div><div class="n" style="font-size:22px">${fmt(x[1])}</div></div>`).join('')}</div><div class="two"><div class="card"><b>Oxirgi 7 kun tushumi</b>${bx(dy)}</div><div class="card"><b>Eng faol guruhlar (davomat)</b>${bx(ga)}</div><div class="card"><b>Eng ko‘p qarzdor guruhlar</b>${bx(gd)}</div><div class="card"><b>Guruhlar bo‘yicha o‘quvchilar (jami ${D.students.length})</b>${bx(D.groups.map(g=>{const c=D.students.filter(s=>s.group==g.id).length;return{n:g.name,v:c,t:c}}))}</div></div>`},
adm(){return`<div class="h"><h2>${hi('adm')} Admin va rollar</h2><button class="btn" onclick="fm('users')">➕ Admin qo‘shish</button><button class="btn o" onclick="rs(0)">♻️ Namuna ma’lumot</button><button class="btn r" onclick="rs(1)">🧹 Bo‘sh boshlash</button></div><div class="card tw"><table><tr><th>Ism</th><th>Email</th><th>Rol</th><th></th></tr>${D.users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td>${u.id==1?'<td></td>':A('users',u.id)}</tr>`).join('')}</table></div><div class="card tw" style="margin-top:16px"><b>Ruxsatlar (Delete ruxsati amalda ishlaydi)</b><table><tr><th>Rol</th>${P.map(p=>`<th>${p}</th>`).join('')}</tr>${Object.keys(D.perm).map(r=>`<tr><td>${r}</td>${P.map(p=>`<td><input type="checkbox" style="width:auto" ${D.perm[r][p]?'checked':''} ${r=='Super Admin'?'disabled':''} onchange="D.perm['${r}'].${p}=this.checked?1:0;save();toast('✅ Saqlandi')"></td>`).join('')}</tr>`).join('')}</table></div>`},
gd(){if(!mg().some(x=>x.id==GD))return`<div class="card">Guruh topilmadi <button class="btn" onclick="go('groups')">◀ Guruhlar</button></div>`;
const g=G(GD),s=D.students.filter(x=>x.group==GD),t=td(),st=x=>D.att[t+'|'+x.id],pd=s.reduce((a,x)=>a+x.paid,0),tt=s.reduce((a,x)=>a+x.price,0),a=s.filter(x=>['k','l'].includes(st(x))).length,pp=Math.round(pd/(tt||1)*100);
const dot=v=>v?`<span class="ac ${v}" style="width:26px;height:26px;font-size:13px" title="Bugun: ${AL[v][1]}">${AL[v][0]}</span>`:'<span class="ac" style="width:26px;height:26px" title="Bugun belgilanmagan"></span>';
return`<div class="h"><button class="btn o" onclick="go('groups')">◀ Guruhlar</button><h2>${hi('groups')} ${esc(g.name)}</h2><button class="btn" onclick="fm('students');$('#f_group').value=GD">➕ O‘quvchi qo‘shish</button></div>
<div class="grid">${[['👨‍🏫','O‘qituvchi',esc(T(g.teacher).name)],['🕒','Jadval',esc(g.time)],['💰','Oylik to‘lov',fmt(g.price)+' so‘m'],['📈','Davomat',pc(gAtt(GD))]].map(x=>`<div class="card gsc"><span class="gi">${x[0]}</span><div><div class="mut">${x[1]}</div><b>${x[2]}</b></div></div>`).join('')}</div>
<div class="gd2"><div class="card"><b>👨‍🎓 O‘quvchilar (${s.length})</b><div class="sl">${s.map(x=>`<div class="sr"><span class="av">${ini(x.name)}</span><div class="si"><b>${esc(x.name)}</b><span class="mut">${esc(x.phone||'')}</span></div>${dot(st(x))}${bg(x)}<button class="btn r s" onclick="del('students',${x.id})">🗑</button></div>`).join('')||'<p class="mut">O‘quvchi yo‘q</p>'}</div></div>
<div class="card"><b>📅 Bugungi davomat: ${a}/${s.length}</b><div class="bar" style="margin:8px 0"><i style="width:${Math.round(a/(s.length||1)*100)}%"></i></div><p><button class="btn o s" onclick="AG=GD;go('att')">Davomat belgilash</button></p><b>💳 To‘lovlar: ${fmt(pd)} / ${fmt(tt)}</b><div class="bar" style="margin:8px 0"><i style="width:${pp}%"></i></div><p class="mut">Qarz: ${fmt(Math.max(0,tt-pd))} so‘m · ${pp}% to‘langan</p><b>📊 Statistika</b><p class="mut">To‘liq to‘laganlar: ${s.filter(x=>x.paid>=x.price).length} · Qarzdorlar: ${s.filter(x=>x.paid<x.price).length}</p></div></div>`},
logs(){return`<div class="h"><h2>${hi('logs')} Activity Logs</h2><button class="btn r" onclick="clr('logs')">🗑 Tozalash</button></div><div class="card tw"><table><tr><th>Admin</th><th>Action</th><th>Target</th><th>Sana</th><th>Oldingi → Yangi</th></tr>${D.logs.map(l=>`<tr><td>${l.who}</td><td>${l.a}</td><td>${l.t}</td><td>${l.d}</td><td>${l.o?l.o+' → '+l.n:'—'}</td></tr>`).join('')||'<tr><td class="mut">Hali amal yo‘q</td></tr>'}</table></div>`}};
function stTb(){const q=Q.toLowerCase(),r=ms().filter(s=>(s.name+s.phone+G(s.group).name).toLowerCase().includes(q)&&(!GF||s.group==GF)&&(!PF||ps(s)[0]==PF));VIS=r.map(s=>s.id);
$('#tb').innerHTML=`<table><tr><th><input type="checkbox" style="width:auto" title="Hammasini tanlash" ${r.length&&r.every(s=>SEL.has(s.id))?'checked':''} onchange="selAll(this.checked)"></th><th>O‘quvchi</th><th>Telefon</th><th>Guruh</th><th>Kurs</th><th>Davomat</th><th>To‘lov</th><th></th></tr>${r.map(s=>`<tr><td><input type="checkbox" style="width:auto" ${SEL.has(s.id)?'checked':''} onchange="sel(${s.id},this.checked)"></td><td><span class="av">${ini(s.name)}</span>${s.name}</td><td>${s.phone}</td><td>${G(s.group).name}</td><td>${G(s.group).course||'—'}</td><td>${pc(sAtt(s.id))}</td><td>${bg(s)}</td>${A('students',s.id)}</tr>`).join('')||'<tr><td class="mut">Topilmadi</td></tr>'}</table>`;upd()}
function sAtt(id){const k=Object.keys(D.att).filter(x=>x.endsWith('|'+id));return k.length?Math.round(k.filter(x=>D.att[x]!='x').length/k.length*100):null}
function gAtt(g){const s=D.students.filter(x=>x.group==g),v=Object.keys(D.att).filter(k=>s.some(x=>k.endsWith('|'+x.id)));return v.length?Math.round(v.filter(k=>D.att[k]!='x').length/v.length*100):null}
function am(d){AM=d?new Date(AM.getFullYear(),AM.getMonth()+d,1):new Date();AS=1;render()}
function attRefresh(){const sc=$('#atw')?$('#atw').scrollLeft:0;render();const w=$('#atw');if(w)w.scrollLeft=sc}
function closePP(){const p=document.getElementById('pp');p&&p.remove()}
function ap(e,sid,dt){e.stopPropagation();closePP();const z=D.students.find(x=>x.id==sid);if(!z)return;const cur=D.att[dt+'|'+sid],r=e.currentTarget.getBoundingClientRect(),by=D.attby&&D.attby[dt+'|'+z.group],p=document.createElement('div');p.id='pp';p.className='pp';p.onclick=ev=>ev.stopPropagation();
p.innerHTML=`<div class="pph"><b>${esc(z.name)}</b><div class="mut">${dt}${by?' · '+esc(by.by)+' '+by.t:''}</div></div>`+['k','l','x'].map(v=>`<button class="pb ${cur==v?'on':''}" onclick="mk(${sid},'${dt}','${v}')"><span class="ac ${v}">${AL[v][0]}</span>${AL[v][1]}</button>`).join('')+(cur?`<button class="pb" onclick="mk(${sid},'${dt}',null)"><span class="ac">↺</span>Tozalash</button>`:'');
document.body.append(p);const w=p.offsetWidth,h=p.offsetHeight;p.style.left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2))+'px';p.style.top=(r.bottom+h+12>innerHeight?Math.max(8,r.top-h-8):r.bottom+8)+'px'}
function mk(sid,dt,v){const z=D.students.find(x=>x.id==sid);if(!z)return;const k=dt+'|'+sid,gk=dt+'|'+z.group,old=D.att[k];if(v)D.att[k]=v;else delete D.att[k];
D.attby=D.attby||{};const pv=D.attby[gk];D.attby[gk]={by:U.name,t:new Date().toLocaleTimeString('ru-RU').slice(0,5)};if(!pv||pv.by!=U.name)D.notes.unshift({t:'📅 '+esc(U.name)+' — '+esc(G(z.group).name)+' davomatini belgiladi ('+dt+')',r:0,to:'staff'});
log('Davomat',z.name+' · '+dt,old?AL[old][1]:'—',v?AL[v][1]:'—');closePP();attRefresh()}
function tp(id){const s=D.students.find(x=>x.id==id);if(!s)return;if(!(s.price>0)){toast('⚠️ Oylik to‘lov summasi kiritilmagan','w');return}
const mkp=(a,ty)=>({sid:s.id,no:pno(),name:s.name,group:G(s.group).name,amount:a,date:td(),type:ty,admin:U.name});
if(s.paid>=s.price){if(!D.perm[U.prole].Edit){toast('⚠️ Sizda tahrirlash huquqi yo‘q','w');return}
ask({t:'To‘lov qaytarilsinmi?',m:'<b>'+esc(s.name)+'</b><br>'+fmt(s.paid)+' so‘m qaytariladi va “to‘lanmagan” deb belgilanadi.',y:'Ha, qaytarish',i:'↩️'},()=>{const o=s.paid;D.pay.push(mkp(-o,'Qaytarildi'));s.paid=0;D.notes.unshift({t:'↩️ To‘lov qaytarildi: '+esc(s.name),r:0,to:'staff'});log('Payment Refunded','Student: '+s.name,fmt(o),'0');render();toast('↩️ To‘lanmadi deb belgilandi')})}
else{const o=s.paid,a=s.price-o;D.pay.push(mkp(a,'Naqd'));s.paid=s.price;D.notes.unshift({t:'💰 Yangi to‘lov: '+esc(s.name),r:0,to:'staff'});log('Payment Updated','Student: '+s.name,fmt(o),fmt(s.paid));render();toast('✅ To‘langan deb belgilandi')}}
function pm(id){const s=D.students.find(x=>x.id==id);mo(`<h3>💳 To‘lov: ${s.name}</h3><label>Summa</label><input id="pa" type="number" value="${s.price-s.paid}"><label>To‘lov turi</label><select id="pt"><option>Naqd</option><option>Karta</option><option>Payme</option><option>Click</option></select><br><br><button class="btn g" onclick="dp(${id})">To‘lash</button> <button class="btn o" onclick="cm()">Bekor</button>`)}
function dp(id){const s=D.students.find(x=>x.id==id),a=Math.min(+$('#pa').value,s.price-s.paid);if(!(a>0)){toast('❌ Summa noto‘g‘ri','e');return}
const o=s.paid;s.paid+=a;const p={sid:s.id,no:pno(),name:s.name,group:G(s.group).name,amount:a,date:td(),type:$('#pt').value,admin:U.name};D.pay.push(p);
D.notes.unshift({t:'💰 Yangi to‘lov: '+s.name,r:0});log('Payment Updated','Student: '+s.name,fmt(o),fmt(s.paid));cm();render();toast('✅ To‘lov muvaffaqiyatli amalga oshirildi');rc(p)}
function rc(p){mo(`<div class="receipt"><h3>${p.amount<0?'↩️ QAYTARISH CHEKI':'🧾 CHEK'} ${p.no}</h3>Student: ${p.name}<br>Group: ${p.group}<br>Amount: ${fmt(p.amount)} so‘m<br>Date: ${p.date}<br>Payment type: ${p.type}<br>Admin: ${p.admin}</div><br><button class="btn" onclick="print()">🖨 Print / PDF</button> <button class="btn o" onclick="cm()">Yopish</button>`)}
function sm(e){e.preventDefault();const b=$('#mb'),v=i=>$('#'+i).value.trim();b.innerHTML='<span class="spin"></span>';const o={name:v('m1'),phone:v('m2'),email:v('m3'),subj:v('m4'),text:v('m5')};
setTimeout(()=>{D.msgs.unshift({id:nid(D.msgs),...o,st:0,d:new Date().toLocaleString('ru-RU'),from:U.email||''});D.notes.unshift({t:'🔔 Yangi xabar: '+esc(o.subj)+' — '+esc(o.name),r:0,to:'staff',g:'msgs'});log('Xabar yuborildi',o.subj);save();render();toast('✅ Xabaringiz yuborildi — barcha adminlarga (Super Admin ham) yetkazildi!')},900);return false}
function editContact(){const c=D.contact;mo(`<h3>✏️ Aloqa ma’lumotlarini o‘zgartirish</h3><label>📞 Telefon</label><input id="c1" value="${esc(c.phone)}"><label>📧 Email</label><input id="c2" value="${esc(c.email)}"><label>💬 Telegram</label><input id="c3" value="${esc(c.tg)}"><label>📍 Manzil</label><input id="c4" value="${esc(c.addr)}"><br><br><button class="btn g" onclick="saveContact()">Saqlash</button> <button class="btn o" onclick="cm()">Bekor</button>`)}
function saveContact(){const v=i=>$('#'+i).value.trim();D.contact={phone:v('c1'),email:v('c2'),tg:v('c3'),addr:v('c4')};log('Tahrirlandi','Aloqa ma’lumotlari');cm();render();toast('✅ Saqlandi')}
function ms2(id,s){D.msgs.find(m=>m.id==id).st=s;save();render()}
function csv(){const t='Ism,Telefon,Guruh,Oylik,Tolangan\n'+D.students.map(s=>[s.name,s.phone,G(s.group).name,s.price,s.paid].join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/csv'}));a.download='oquvchilar.csv';a.click()}
function evs(d){const a=[],w=new Date(d).getUTCDay();if(+d.slice(8)==10)a.push(['💳','To‘lov deadline: '+D.students.filter(s=>s.paid<s.price).length+' qarzdor']);D.pay.filter(p=>p.date==d).forEach(p=>a.push(['💰',p.name+' — '+fmt(p.amount)]));if(Object.keys(D.att).some(k=>k.startsWith(d)))a.push(['📅','Davomat belgilangan']);D.ev.filter(e=>e.date==d).forEach(e=>a.push(['📢',e.text,e.id]));if([1,3,5].includes(w))a.push(['📚','Du-Chor-Ju guruhlari darsi']);if([2,4,6].includes(w))a.push(['📚','Sesh-Pay-Shan guruhlari darsi']);return a}
const bx=a=>{const mx=Math.max(1,...a.map(x=>x.v));return`<div class="bars">${a.map(x=>`<div><span>${x.t!=null?x.t:(x.v?fmt(x.v/1000)+'k':'0')}</span><b style="height:${x.v/mx*140+4}px"></b>${x.n}</div>`).join('')}</div>`};
function up(i){[...i.files].forEach(f=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),k=Math.min(1,800/im.width);c.width=im.width*k;c.height=im.height*k;c.getContext('2d').drawImage(im,0,0,c.width,c.height);D.media.push({id:nid(D.media),name:f.name,cat:$('#mc').value,src:c.toDataURL('image/jpeg',.8)});log('Media yuklandi',f.name);render();toast('✅ Yuklandi')};im.src=r.result};r.readAsDataURL(f)})}
function rn(id){const m=D.media.find(x=>x.id==id);pr('Yangi nom',m.name,n=>{if(n){m.name=n;log('Media tahrirlandi',n);render()}})}
function clr(k){if(!D.perm[U.prole].Delete){toast('⚠️ Sizda o‘chirish huquqi yo‘q','w');return}ask({t:'Hammasi tozalansinmi?',m:'Bu amalni ortga qaytarib bo‘lmaydi.',y:'Ha, tozalash'},()=>{D[k]=[];save();render();toast('✅ Tozalandi')})}
function dpay(i){if(!D.perm[U.prole].Delete){toast('⚠️ Sizda o‘chirish huquqi yo‘q','w');return}const p=D.pay[i];if(!p)return;
ask({t:'Chek o‘chirilsinmi?',m:p.amount<0?'Qaytarish cheki o‘chiriladi va '+fmt(-p.amount)+' so‘m o‘quvchiga qayta yoziladi.':'To‘lov summasi o‘quvchidan ayiriladi.',y:'Ha, o‘chirish'},()=>{const j=D.pay.indexOf(p),st=D.students.find(x=>x.id==p.sid)||D.students.find(x=>x.name==p.name);if(st)st.paid=Math.max(0,st.paid-p.amount);D.pay.splice(j,1);log('To‘lov o‘chirildi',p.name,fmt(p.amount),'0');render();toast('✅ O‘chirildi')})}
function rs(w){ask({t:w?'Bo‘sh boshlansinmi?':'Namuna ma’lumot tiklansinmi?',m:w?'Barcha ma’lumot o‘chirilib, bo‘sh boshlanadi.':'Hozirgi ma’lumotlar namunaviy ma’lumotga almashtiriladi.',y:'Davom etish',i:'♻️'},()=>{const u=D.users,pm=D.perm,ct=D.contact;if(w){D={students:[],groups:[],teachers:[],courses:[],ann:[],msgs:[],pay:[],att:{},logs:[],notes:[],media:[],ev:[],users:u,perm:pm}}else{D=seed();D.media=[];D.ev=[];D.users=u;D.perm=pm}D.contact=ct;save();render();toast('✅ Bajarildi')})}
const pc=v=>v==null?'—':v+'%';
const lg=z=>`<span class="lc" style="width:${z}px;height:${z}px;--ph:-${(performance.now()/1000%6).toFixed(2)}s"><img src="${LOGO}" alt=""></span>`;
function upd(){const b=$('#bd');if(b)b.textContent='🗑 O‘chirish ('+SEL.size+')';b.hidden=!SEL.size}
function sel(id,c){c?SEL.add(id):SEL.delete(id);upd()}
function selAll(c){VIS.forEach(id=>c?SEL.add(id):SEL.delete(id));stTb()}
function bulk(){if(!D.perm[U.prole].Delete){toast('⚠️ Sizda o‘chirish huquqi yo‘q','w');return}if(!SEL.size){toast('⚠️ Avval o‘quvchilarni belgilang','w');return}const n=SEL.size;
ask({t:n+' ta o‘quvchi o‘chirilsinmi?',m:'Bu amalni ortga qaytarib bo‘lmaydi.',y:'Ha, o‘chirish'},()=>{D.students=D.students.filter(s=>!SEL.has(s.id));Object.keys(D.att).forEach(k=>{if(SEL.has(+k.split('|')[1]))delete D.att[k]});SEL.clear();log('O‘chirildi',n+' ta o‘quvchi');render();toast('✅ '+n+' ta o‘quvchi o‘chirildi')})}
function ask(o,yes){const c=o.c||'r',m=document.createElement('div');m.className='mo cf';m.innerHTML=`<div class="card cfc"><div class="cfi ${c}">${o.i||'⚠️'}</div><h3>${o.t}</h3><p class="mut">${o.m||''}</p><div class="cfb"><button class="btn o" id="cfn">Bekor qilish</button><button class="btn ${c}" id="cfy">${o.y||'Ha'}</button></div></div>`;
m.onclick=e=>{if(e.target==m)m.remove()};document.body.append(m);m.querySelector('#cfn').onclick=()=>m.remove();m.querySelector('#cfy').onclick=()=>{m.remove();yes()};m.querySelector('#cfy').focus()}
function pr(t,v,cb){const m=document.createElement('div');m.className='mo cf';m.innerHTML=`<div class="card cfc" style="text-align:left"><h3>${t}</h3><input id="prv" value="${esc(v)}"><div class="cfb" style="margin-top:16px"><button class="btn o" id="prn">Bekor</button><button class="btn g" id="pry">Saqlash</button></div></div>`;
const ok=()=>{const x=m.querySelector('#prv').value.trim();m.remove();cb(x)};m.onclick=e=>{if(e.target==m)m.remove()};document.body.append(m);m.querySelector('#prn').onclick=()=>m.remove();m.querySelector('#pry').onclick=ok;const i=m.querySelector('#prv');i.onkeydown=e=>{if(e.key=='Enter')ok()};i.focus();i.select()}
document.addEventListener('click',closePP);document.addEventListener('keydown',e=>{if(e.key=='Escape'){closePP();const m=document.querySelector('.mo');m&&m.remove()}});
try{if(localStorage.jt)document.documentElement.dataset.theme=localStorage.jt}catch(e){}
restore();render();
